// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE6G1MUgDxkGHY9dq7MS7H_WNYGLFWUI0',
    appId: '1:425485723417:web:c009a5f31f0542a4dd0788',
    messagingSenderId: '425485723417',
    projectId: 'parafalbd',
    authDomain: 'parafalbd.firebaseapp.com',
    storageBucket: 'parafalbd.firebasestorage.app',
    measurementId: 'G-BWS2L5F5QE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9E4LV1e_mIHvWOiWv-s6wgiKGMZTK3nM',
    appId: '1:425485723417:android:d0dbec29773b248ddd0788',
    messagingSenderId: '425485723417',
    projectId: 'parafalbd',
    storageBucket: 'parafalbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjYYAKUqs0-42bwYq6QYsm3Pwfd5w64Ak',
    appId: '1:425485723417:ios:47f1830c9af79e73dd0788',
    messagingSenderId: '425485723417',
    projectId: 'parafalbd',
    storageBucket: 'parafalbd.firebasestorage.app',
    iosBundleId: 'com.example.gerenciadorClientes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjYYAKUqs0-42bwYq6QYsm3Pwfd5w64Ak',
    appId: '1:425485723417:ios:47f1830c9af79e73dd0788',
    messagingSenderId: '425485723417',
    projectId: 'parafalbd',
    storageBucket: 'parafalbd.firebasestorage.app',
    iosBundleId: 'com.example.gerenciadorClientes',
  );
}
